const itens = {
    "results": [
        {
        "id": 1,
        "nome": "Tênis de Corrida",
        "descricao": "Tênis leve e confortável para corrida.",
        "preco": 499.90,
        "categoria": "Esportes",
        "estoque": 50,
        "imagem": "https://rmilet.vteximg.com.br/arquivos/ids/8223080-593-593/Tenis-de-Corrida-Branco-Reverso-II-%7C-Olympikus-Tamanho--37---Cor--BRANCO-0.jpg?v=638321226289870000",
        "marca": "Marca AO",
        "avaliacoes": []
        },
        {
        "id": 2,
        "nome": "Liquidificador",
        "descricao": "Liquidificador com potência de 600W e 5 velocidades.",
        "preco": 299.90,
        "categoria": "Eletrodomésticos",
        "estoque": 40,
        "imagem": "https://freitasvarejo.vteximg.com.br/arquivos/ids/184960/L99-FB1.jpg?v=638319570312570000",
        "marca": "Marca AP",
        "avaliacoes": []
        },
        {
        "id": 3,
        "nome": "Tablet",
        "descricao": "Tablet com tela de 10 polegadas e 64GB de armazenamento.",
        "preco": 1499.90,
        "categoria": "Eletrônicos",
        "estoque": 20,
        "imagem": "https://samsungbrshop.vtexassets.com/arquivos/ids/223799-600-auto?v=638334095344430000&width=600&height=auto&aspect=true",
        "marca": "Marca AQ",
        "avaliacoes": []
        },
        {
        "id": 4,
        "nome": "Cafeteira Elétrica",
        "descricao": "Cafeteira com jarra de vidro e capacidade para 12 xícaras.",
        "preco": 199.90,
        "categoria": "Eletrodomésticos",
        "estoque": 60,
        "imagem": "https://t62533.vteximg.com.br/arquivos/ids/280620-1000-1000/cafeteira-mondial-pratic-cn01-20-xicaras-1.jpg?v=638277264847300000",
        "marca": "Marca AR",
        "avaliacoes": []
        },
        {
        "id": 5,
        "nome": "Esmalte de Unha",
        "descricao": "Esmalte com longa duração e secagem rápida.",
        "preco": 29.90,
        "categoria": "Beleza",
        "estoque": 150,
        "imagem": "https://cdn.awsli.com.br/600x450/1233/1233542/produto/96034540/design-sem-nome--44--y5z7mb3fcp.png",
        "marca": "Marca AS",
        "avaliacoes": []
        },
        {
        "id": 6,
        "nome": "Creme Hidratante",
        "descricao": "Creme para pele seca, com extratos naturais.",
        "preco": 89.90,
        "categoria": "Beleza",
        "estoque": 70,
        "imagem": "https://www.drogariaminasbrasil.com.br/media/product/67f/creme-hidratante-corporal-nivea-soft-milk-pele-seca-400-ml-2e5.jpg",
        "marca": "Marca AT",
        "avaliacoes": []
        },
        {
        "id": 7,
        "nome": "Pacote de Snacks",
        "descricao": "Mistura de salgadinhos variados para lanches.",
        "preco": 19.90,
        "categoria": "Alimentos",
        "estoque": 120,
        "imagem": "https://ibassets.com.br/ib.item.image.big/b-21202c9635bd435c8092c52760bd9c30.jpeg",
        "marca": "Marca AU",
        "avaliacoes": []
        },
        {
        "id": 8,
        "nome": "Batedeira",
        "descricao": "Batedeira com tigela de 4,5L e 3 velocidades.",
        "preco": 399.90,
        "categoria": "Eletrodomésticos",
        "estoque": 25,
        "imagem": "https://martinelloeletrodomesticos.fbitsstatic.net/img/p/batedeira-planetaria-mondial-bp-03-b-220v-77669/264261.jpg?w=482&h=482&v=no-change&qs=ignore",
        "marca": "Marca AV",
        "avaliacoes": []
        },
        {
        "id": 9,
        "nome": "Vestido de Verão",
        "descricao": "Vestido leve e confortável para dias quentes.",
        "preco": 129.90,
        "categoria": "Vestuário",
        "estoque": 80,
        "imagem": "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcR-uOYaa4lL38uatSVTS-NPfSt7hFG3KJ6ccH43of-KvkEg_oYCFhBJuCaNkLkZUDTKF5w2yzGonYDvGJejpR88ROXHH7ln-i9hm0LEUXrQXLAHQ8w4UqBV&usqp=CAE",
        "marca": "Marca AW",
        "avaliacoes": []
        },
        {
        "id": 10,
        "nome": "Almofada Decorativa",
        "descricao": "Almofada com estampa moderna para sofá.",
        "preco": 59.90,
        "categoria": "Decoração",
        "estoque": 100,
        "imagem": "https://1279028l.ha.azioncdn.net/img/2018/02/produto/7074/ani1014b.jpg?ims=810x810",
        "marca": "Marca AX",
        "avaliacoes": []
        },
        {
        "id": 11,
        "nome": "Monitor Full HD",
        "descricao": "Monitor de 24 polegadas com resolução Full HD.",
        "preco": 899.90,
        "categoria": "Eletrônicos",
        "estoque": 30,
        "imagem": "https://lojaibyte.vteximg.com.br/arquivos/ids/366910-1200-1200/monitor-gamer-samsung-24-fhd-75hz-hdmi-vga-freesync-preto-serie-t350-01-min-min.jpg?v=637717187543130000",
        "marca": "Marca AY",
        "avaliacoes": []
        },
        {
        "id": 12,
        "nome": "Teclado Mecânico",
        "descricao": "Teclado mecânico com retroiluminação RGB.",
        "preco": 299.90,
        "categoria": "Eletrônicos",
        "estoque": 40,
        "imagem": "https://cdn.iset.io/assets/00665/produtos/5471/teclado-hyperx-alloy-origins-core-rgb-tkl-abnt2-hx-kb7rdx-br-01.png",
        "marca": "Marca AZ",
        "avaliacoes": []
        },
        {
        "id": 13,
        "nome": "Carteira de Couro",
        "descricao": "Carteira elegante com diversos compartimentos.",
        "preco": 129.90,
        "categoria": "Acessórios",
        "estoque": 60,
        "imagem": "https://73851.cdn.simplo7.net/static/73851/sku/acessorios-carteira-em-couro-encaixe--p-1637356285245.jpeg",
        "marca": "Marca BA",
        "avaliacoes": []
        },
        {
        "id": 14,
        "nome": "Cinto de Couro",
        "descricao": "Cinto de couro legítimo, ajustável.",
        "preco": 79.90,
        "categoria": "Acessórios",
        "estoque": 90,
        "imagem": "https://images.tcdn.com.br/img/img_prod/747651/cinto_feminino_em_couro_legitimo_303_1_8f6b5a88b05a051c01b97d4e0eda01ad.jpg",
        "marca": "Marca BB",
        "avaliacoes": []
        },
        {
        "id": 15,
        "nome": "Jaqueta Jeans",
        "descricao": "Jaqueta jeans clássica, perfeita para qualquer ocasião.",
        "preco": 199.90,
        "categoria": "Vestuário",
        "estoque": 50,
        "imagem": "https://cdn.iset.io/assets/66687/produtos/17921/e66e146bf729741cdbb10809b6697ba76569eb3db4da2.png",
        "marca": "Marca BC",
        "avaliacoes": []
        },
        {
        "id": 16,
        "nome": "Bola de Futebol",
        "descricao": "Bola oficial de futebol, ideal para jogos.",
        "preco": 149.90,
        "categoria": "Esportes",
        "estoque": 80,
        "imagem": "https://goroller.com.br/cdn/shop/files/bolafutebolmare_1024x1024.webp?v=1708607537",
        "marca": "Marca BD",
        "avaliacoes": []
        },
        {
        "id": 17,
        "nome": "Espelho de Maquiagem",
        "descricao": "Espelho com luz LED e aumento.",
        "preco": 99.90,
        "categoria": "Beleza",
        "estoque": 100,
        "imagem": "https://www.rodioffice.com.br/assets/img/produtos/produto-2115-673-821818.jpg",
        "marca": "Marca BE",
        "avaliacoes": []
        },
        {
        "id": 18,
        "nome": "Ventilador de Mesa",
        "descricao": "Ventilador de mesa com 3 velocidades.",
        "preco": 159.90,
        "categoria": "Eletrodomésticos",
        "estoque": 75,
        "imagem": "https://mirandacomputacao.jetassets.com.br/produto/45142-principal.png",
        "marca": "Marca BF",
        "avaliacoes": []
        },
        {
        "id": 19,
        "nome": "Fone Bluetooth",
        "descricao": "Fone sem fio com cancelamento de ruído.",
        "preco": 199.90,
        "categoria": "Eletrônicos",
        "estoque": 30,
        "imagem": "https://edifier.com.br/pub/media/catalog/product/f/o/fone-bluetooth-edifier-w600bt-pret.jpg",
        "marca": "Marca BG",
        "avaliacoes": []
        },
        {
        "id": 20,
        "nome": "Bolsinha de Ombro",
        "descricao": "Bolsinha prática para uso diário.",
        "preco": 89.90,
        "categoria": "Acessórios",
        "estoque": 50,
        "imagem": "https://a-static.mlcdn.com.br/450x450/bolsa-feminina-transversal-lateral-ombro-bolsinha-pequena-festa-alca-corrente-mini-bag-luxo-chique-dashuri/dashuri/7d49951e2c8c11eea0294201ac18502e/88147430a9eb30d4c547f85766072903.jpeg",
        "marca": "Marca BH",
        "avaliacoes": []
        },
        {
        "id": 21,
        "nome": "Bicicleta Aro 29",
        "descricao": "Bicicleta MTB com quadro de alumínio e suspensão.",
        "preco": 899.90,
        "categoria": "Esportes",
        "estoque": 30,
        "imagem": "https://cdn.awsli.com.br/600x1000/2647/2647048/produto/25256789236aa1778a9.jpg",
        "marca": "Marca U",
        "avaliacoes": []
        },
        {
        "id": 22,
        "nome": "Fritadeira Sem Óleo",
        "descricao": "Fritadeira elétrica com tecnologia de ar quente.",
        "preco": 349.90,
        "categoria": "Eletrodomésticos",
        "estoque": 25,
        "imagem": "https://suggar.fbitsstatic.net/img/p/fritadeira-sem-oleo-light-fry-4-litros-preta-suggar-64156/231025-4.jpg?w=1200&h=1200&v=no-value",
        "marca": "Marca V",
        "avaliacoes": []
        },
        {
        "id": 23,
        "nome": "Câmera Digital",
        "descricao": "Câmera DSLR com lente 18-55mm.",
        "preco": 2499.90,
        "categoria": "Eletrônicos",
        "estoque": 10,
        "imagem": "https://cdn.awsli.com.br/600x450/590/590974/produto/24482905/bb6e7ba7e8.jpg",
        "marca": "Marca W",
        "avaliacoes": []
        },
        {
        "id": 24,
        "nome": "Impressora Multifuncional",
        "descricao": "Impressora que imprime, copia e digitaliza.",
        "preco": 499.90,
        "categoria": "Eletrônicos",
        "estoque": 50,
        "imagem": "https://images.tcdn.com.br/img/img_prod/1130603/impressora_multifuncional_laser_mono_hp_m432fdn_5323423_1_138e00371329ec31d473fedad9b38509.jpg",
        "marca": "Marca X",
        "avaliacoes": []
        },
        {
        "id": 25,
        "nome": "Conjunto de Pincéis",
        "descricao": "Conjunto com 10 pincéis para maquiagem.",
        "preco": 79.90,
        "categoria": "Beleza",
        "estoque": 100,
        "imagem": "https://images-americanas.b2w.io/produtos/39055963/imagens/kit-pinceis-pincel-maquiagem-kabuki-profissional/39055965_1_large.jpg",
        "marca": "Marca Y",
        "avaliacoes": []
        },
        {
        "id": 26,
        "nome": "Perfume Masculino",
        "descricao": "Perfume com notas amadeiradas e frescas.",
        "preco": 199.90,
        "categoria": "Beleza",
        "estoque": 40,
        "imagem": "https://a-static.mlcdn.com.br/450x450/perfume-masculino-importado-original-black-125-ml-edt-volarium/lojavolarium/15984266187/7cb2b932a57a0603aa0439e1e75bd0a4.jpeg",
        "marca": "Marca Z",
        "avaliacoes": []
        },
        {
        "id": 27,
        "nome": "Cesta de Café da Manhã",
        "descricao": "Cesta com produtos selecionados para café da manhã.",
        "preco": 129.90,
        "categoria": "Alimentos",
        "estoque": 60,
        "imagem": "https://cestascompany.com.br/cdn/shop/files/Cesta-Cafe-da-Manha-Presente2.jpg?v=1683723069&width=1946",
        "marca": "Marca AA",
        "avaliacoes": []
        },
        {
        "id": 28,
        "nome": "Conjunto de Facas",
        "descricao": "Conjunto de 5 facas de cozinha com suporte.",
        "preco": 199.90,
        "categoria": "Eletrodomésticos",
        "estoque": 35,
        "imagem": "https://electrolux.vtexassets.com/arquivos/ids/214622/Bloco_bambu_1000x1000-principal.jpg?v=637721977670100000",
        "marca": "Marca AB",
        "avaliacoes": []
        },
        {
        "id": 29,
        "nome": "Roupão de Banho",
        "descricao": "Roupão de banho em algodão macio.",
        "preco": 149.90,
        "categoria": "Vestuário",
        "estoque": 80,
        "imagem": "https://down-br.img.susercontent.com/file/sg-11134201-23030-8ux37qi0whovd4",
        "marca": "Marca AC",
        "avaliacoes": []
        },
        {
        "id": 30,
        "nome": "Tapete Antiderrapante",
        "descricao": "Tapete ideal para banheiro ou cozinha.",
        "preco": 79.90,
        "categoria": "Decoração",
        "estoque": 120,
        "imagem": "https://down-br.img.susercontent.com/file/587cb7451a24045d2b14bfb82f43b43c",
        "marca": "Marca AD",
        "avaliacoes": []
        },
        {
        "id": 31,
        "nome": "Smartwatch",
        "descricao": "Relógio inteligente com monitoramento de saúde.",
        "preco": 399.90,
        "categoria": "Eletrônicos",
        "estoque": 45,
        "imagem": "https://m.media-amazon.com/images/I/91Q0Ln0cv5L._AC_UF1000,1000_QL80_.jpg",
        "marca": "Marca AE",
        "avaliacoes": []
        },
        {
        "id": 32,
        "nome": "Fones de Ouvido In-Ear",
        "descricao": "Fones de ouvido intra-auriculares com isolamento.",
        "preco": 99.90,
        "categoria": "Eletrônicos",
        "estoque": 150,
        "imagem": "https://edifier.com.br/pub/media/catalog/product/cache/f1731b22860b0086fc34e14d5ee03543/p/2/p205-carrossel-03.jpg",
        "marca": "Marca AF",
        "avaliacoes": []
        },
        {
        "id": 33,
        "nome": "Relógio Analógico",
        "descricao": "Relógio com design clássico e pulseira de couro.",
        "preco": 299.90,
        "categoria": "Acessórios",
        "estoque": 25,
        "imagem": "https://carrefourbr.vtexassets.com/arquivos/ids/63873102/718a81bdfc094deaacea68dd82e5454c.jpg?v=637929209172370000",
        "marca": "Marca AG",
        "avaliacoes": []
        },
        {
        "id": 34,
        "nome": "Cordão",
        "descricao": "Uma linda joia para qualquer ocasião",
        "preco": 79.90,
        "categoria": "Acessórios",
        "estoque": 100,
        "imagem": "https://fluiartejoias.vteximg.com.br/arquivos/ids/171986-1200-1200/gargantilha-cordao-feminina-em-ouro-amarelo.jpg?v=637995361388400000",
        "marca": "Marca AH",
        "avaliacoes": []
        },
        {
        "id": 35,
        "nome": "Camiseta Básica",
        "descricao": "Camiseta básica em diversas cores.",
        "preco": 39.90,
        "categoria": "Vestuário",
        "estoque": 200,
        "imagem": "https://cdn.awsli.com.br/1960/1960866/produto/125390796/a12dd9ac46.jpg",
        "marca": "Marca AI",
        "avaliacoes": []
        },
        {
        "id": 36,
        "nome": "Pulseira Fitness",
        "descricao": "Pulseira para monitoramento de atividades físicas.",
        "preco": 149.90,
        "categoria": "Eletrônicos",
        "estoque": 70,
        "imagem": "https://img.irroba.com.br/fit-in/600x600/filters:fill(fff):quality(80)/casaanza/catalog/api/casaanza_citelirr/61ec54314bf25.jpg",
        "marca": "Marca AJ",
        "avaliacoes": []
        },
        {
        "id": 37,
        "nome": "Luminária de Mesa",
        "descricao": "Luminária ajustável para estudos.",
        "preco": 89.90,
        "categoria": "Decoração",
        "estoque": 50,
        "imagem": "https://cdn.leroymerlin.com.br/products/luminaria_de_mesa_articulavel_preta_base_e_presilha_leitura_e_1566920733_bb51_600x600.png",
        "marca": "Marca AK",
        "avaliacoes": []
        },
        {
        "id": 38,
        "nome": "Capa para Celular",
        "descricao": "Capa protetora para diversos modelos de celular.",
        "preco": 49.90,
        "categoria": "Acessórios",
        "estoque": 150,
        "imagem": "https://images.tcdn.com.br/img/img_prod/670412/capa_para_celular_baseus_bright_para_iphone_x_vermelho_1027_1_20181206080306.png",
        "marca": "Marca AL",
        "avaliacoes": []
        },
        {
        "id": 39,
        "nome": "Mouse Pad Gamer",
        "descricao": "Mouse pad grande com superfície em tecido.",
        "preco": 59.90,
        "categoria": "Eletrônicos",
        "estoque": 100,
        "imagem": "https://images.kabum.com.br/produtos/fotos/386885/mousepad-gamer-havit-800x500mm-rgb-usb-preto-mp903_1666894308_gg.jpg",
        "marca": "Marca AM",
        "avaliacoes": []
        },
        {
        "id": 40,
        "nome": "Camiseta Personalizada",
        "descricao": "Camiseta com impressão personalizada a escolha.",
        "preco": 69.90,
        "categoria": "Vestuário",
        "estoque": 80,
        "imagem": "https://cdn.awsli.com.br/600x450/987/987529/produto/2561109473be8ae8006.jpg",
        "marca": "Marca AN",
        "avaliacoes": []
        }
    ]
};

module.exports = itens;